version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo "Installing dependencies"
      - mvn -version

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean package

  post_build:
    commands:
      - echo "Build completed on $(date)"

artifacts:
  files:
    - target/*.war
    - scripts/**/*
  discard-paths: no
  name: my-app.zip